name: Build Windows

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup UV
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install dependencies
        run: uv sync

      - name: Build Windows app
        run: uv run briefcase build windows

      - name: Package Windows app
        run: uv run briefcase package windows

      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*.msi
